import { SITE } from '@/lib/site';

export const metadata = {
  title: 'About',
  description: `Why ${SITE.name} exists and who builds it — a free, accurate Korean verb conjugator made by someone learning the language.`,
  alternates: { canonical: `${SITE.url}/about` },
};

export default function About() {
  return (
    <main className="wrap about">
      <div className="eyebrow rise">About</div>
      <h1 className="about-title rise">Why this exists</h1>

      <div className="about-prose rise rise-2">
        <p>
          I built {SITE.name} because conjugation was the part of learning Korean that
          tripped me up most. I wanted one place where I could type any verb and see every
          form — casual, polite, and formal, across past, present, and future — without
          digging through a textbook each time. So I made it, and put it online free for
          anyone else learning.
        </p>

        <p>
          Getting it <em>right</em> mattered more than getting it fast. Korean&rsquo;s
          irregular verbs — the ㄷ, ㅂ, ㅅ, 르, and 으 patterns, and the rest — are exactly
          where quick tools fall down. Every conjugation here is generated by a
          well-established open-source algorithm and checked against those irregular
          patterns, so the forms you see are the forms people actually use. The
          romanization is a pronunciation aid, not a replacement for reading Hangul.
        </p>

        <h2>Who&rsquo;s behind it</h2>
        <p>
          {/* ↓ Edit these details to your own. First-person and specific is what builds trust. */}
          I&rsquo;m <strong>Matt</strong>, a designer and developer based in
          Jersey, Channel Islands, and I study Korean myself — building this alongside
          a friend and Korean teacher in Seoul. If you spot a form that looks wrong, I
          genuinely want to know: <a href="mailto:seoulfultea@gmail.com">seoulfultea@gmail.com</a>.
        </p>

        <p>
          {SITE.name} is free, has no ads, and isn&rsquo;t a funnel for a paid course.
          It&rsquo;s simply a tool I wanted to exist.
        </p>
      </div>

      <p className="about-back rise rise-3">
        <a href="/">← Browse the verbs</a>
      </p>
    </main>
  );
}
